language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgif-dev
      - g++-4.8
  code_climate:
    repo_token: 07de009e5f4d0a43c51b18f3443b2fe7ddcf3fea206e75c3a81b1c4030657f69
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn lint
  - yarn format:check
  - yarn add gulp@3.9.1
script:
  - gulp
  - yarn test-cov
after_script:
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
