name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2  
    - name: install pre-requisite
      run: sudo apt install python
    - name: install BLEEP
      run: python setup.py --install      
    - name: test BLEEP with (temporary)
      run: |
        export PATH=${PATH}:${GITHUB_WORKSPACE}/Install/bin
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GITHUB_WORKSPACE}/Install
        cd ${GITHUB_WORKSPACE}/build/tests/regtest/shadow-rust/1_hello/debug/; shadow ${GITHUB_WORKSPACE}/tests/regtest/shadow-rust/1_hello/rust_hello.xml
    - name: test BLEEP with verbose
      run: |
        export PATH=${PATH}:${GITHUB_WORKSPACE}/Install/bin
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GITHUB_WORKSPACE}/Install
        mkdir -p build; cd build; cmake ../; make -j8; ctest -VV
    - name: test BLEEP using script
      run: |
        export PATH=${PATH}:${GITHUB_WORKSPACE}/Install/bin
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GITHUB_WORKSPACE}/Install
        python setup.py --test
